### ISSUE TITLE
[CONTRACT] Deadline and expiry semantics: finalize spec parity + pause-mode behavior

### ISSUE THREAD

**Issue by Cedarich** [StayLitCodes/Vaultix#213]
### Goal
Make expiration/refund rules match the time-lock spec and ensure behavior is correct under pause.

### Tasks
- [ ] Verify `refund_expired` eligibility rules match `.kiro/specs/escrow-time-lock-refund/*`
- [ ] Decide and enforce who can trigger refunds (depositor-only vs permissionless trigger)
- [ ] Ensure pause-mode allows (or blocks) `refund_expired` and document rationale
- [ ] Emit refund event with escrow_id, refunded amount, and timestamp
- [ ] Add tests for: deadline not reached, disputed escrow, fully released escrow, paused contract

### Acceptance Criteria
- [ ] Refund rules are aligned with the spec and tested
- [ ] No expired refund can occur before `env.ledger().timestamp() > deadline`
- [ ] Pause-mode behavior is deterministic and tested

**Comment by legend-esc** [comment]
@legend-esc has applied to work on this issue as part of the **Stellar Wave Program**'s 4th wave.


> I’d like to work on this because the contract currently cannot even compile, so fixing these structural issues is a blocker for the entire AMM system.
> 
> My approach would be to systematically repair the Rust compilation errors in `contracts/amm/src/lib.rs`: first align scope issues caused by #86 by ensuring `initialize_with_flash_loan_fee` has the correct parameters (so `admin`, `fee_recipient`, and `protocol_fee_bps` are in scope), then remove the stray closing `);` at line 164, fix mismatched braces by properly closing `withdraw_protocol_fees`, and correct the extra `}` after `get_protocol_fee` and `get_amount_in` so the `impl` block structure is valid. Finally, I’d run full builds and tests (`wasm32v1-none` + `cargo test -p amm`) to ensure everything compiles cleanly with no regressions.
> 


ℹ️ **Repo Maintainers**: To accept this application, [review their application](https://www.drips.network/wave/maintainers/issues/055b4450-c150-485b-abac-6c2c3ed0b568) or assign @legend-esc to this issue.
